default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  reaping_frequency: 10
  username:
  password:
  timeout: 5000

development:
  <<: *default
  database: journal_development

test:
  <<: *default
  database: journal_test
